##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    isaac_usd_path: ""
    usd_path: "robot/fr3/fr3.usd"
    usd_robot_root: "/fr3"
    usd_flip_joints: ["fr3_joint1","fr3_joint2","fr3_joint3","fr3_joint4", "fr3_joint5",
      "fr3_joint6","fr3_joint7","fr3_finger_joint1", "fr3_finger_joint2"]
    usd_flip_joints: {
    "fr3_joint1": "Z",
    "fr3_joint2": "Z",
    "fr3_joint3": "Z",
    "fr3_joint4": "Z",
     "fr3_joint5": "Z",
    "fr3_joint6": "Z",
    "fr3_joint7": "Z",
    "fr3_finger_joint1": "Y",
     "fr3_finger_joint2":  "Y",
    }
    
    usd_flip_joint_limits: ["fr3_finger_joint2"]
    urdf_path: "robot/fr3_description/fr3.urdf"
    asset_root_path: "robot/franka_description"
    base_link: "fr3_link0"
    ee_link: "fr3_hand"
    collision_link_names:
      [
        "fr3_link0",
        "fr3_link1",
        "fr3_link2",
        "fr3_link3",
        "fr3_link4",
        "fr3_link5",
        "fr3_link6",
        "fr3_link7",
        "fr3_hand",
        "fr3_leftfinger",
        "fr3_rightfinger",
        "attached_object",
      ]
    collision_spheres: "spheres/fr3_mesh.yml"
    collision_sphere_buffer: 0.0025 
    extra_collision_spheres: {"attached_object": 4}
    use_global_cumul: True
    self_collision_ignore:
      {
        "fr3_link0": ["fr3_link1", "fr3_link2"],
        "fr3_link1": ["fr3_link2", "fr3_link3", "fr3_link4"],
        "fr3_link2": ["fr3_link3", "fr3_link4"],
        "fr3_link3": ["fr3_link4", "fr3_link6"],
        "fr3_link4":
          ["fr3_link5", "fr3_link6", "fr3_link7", "fr3_link8"],
        "fr3_link5": ["fr3_link6", "fr3_link7", "fr3_hand","fr3_leftfinger", "fr3_rightfinger"],
        "fr3_link6": ["fr3_link7", "fr3_hand", "attached_object", "fr3_leftfinger", "fr3_rightfinger"],
        "fr3_link7": ["fr3_hand", "attached_object", "fr3_leftfinger", "fr3_rightfinger"],
        "fr3_hand": ["fr3_leftfinger", "fr3_rightfinger","attached_object"],
        "fr3_leftfinger": ["fr3_rightfinger", "attached_object"],
        "fr3_rightfinger": ["attached_object"],
        
      }
    
    self_collision_buffer:
      {
        "fr3_link0": 0.1, 
        "fr3_link1": 0.05, 
        "fr3_link2": 0.0,
        "fr3_link3": 0.0,
        "fr3_link4": 0.0,
        "fr3_link5": 0.0,
        "fr3_link6": 0.0,
        "fr3_link7": 0.0,
        "fr3_hand": 0.02,
        "fr3_leftfinger": 0.01,
        "fr3_rightfinger": 0.01,
        "attached_object": 0.0,
      }
    #link_names: ["fr3_link4"]
    mesh_link_names:
      [
        "fr3_link0",
        "fr3_link1",
        "fr3_link2",
        "fr3_link3",
        "fr3_link4",
        "fr3_link5",
        "fr3_link6",
        "fr3_link7",
        "fr3_hand",
        "fr3_leftfinger",
        "fr3_rightfinger",
      ]
    lock_joints: {"fr3_finger_joint1": 0.04, "fr3_finger_joint2": 0.04}
    extra_links: {"attached_object":{"parent_link_name": "fr3_hand" , 
    "link_name": "attached_object", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
    "joint_name": "attach_joint" }}
    cspace:
      joint_names: ["fr3_joint1","fr3_joint2","fr3_joint3","fr3_joint4", "fr3_joint5",
      "fr3_joint6","fr3_joint7","fr3_finger_joint1", "fr3_finger_joint2"]
      retract_config: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]
      null_space_weight: [1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1]
      max_acceleration: 15.0
      max_jerk: 500.0